### ISSUE TITLE
Apple pay is showing on Chrome browsers

### ISSUE THREAD

**Issue by dhacquebord** [MultiSafepay/magento2-hyva-checkout#14]
The Apple pay method is hidden on Chrome devices when using the default Magento Checkout. But when we are using this module for the Hyvä Checkout it is still showing.

**Comment by vinodsowdagar** [comment]
Hi @dhacquebord ,

Thanks for opening this issue. It seems we are missing some checks on the javascript side. We've confirmed this issue and are going to work on a fix next sprint. We'll keep you updated on the development.

**Comment by vinodsowdagar** [comment]
Hi @dhacquebord ,

This has been released: https://github.com/MultiSafepay/magento2-hyva-checkout/releases/tag/2.2.1

I'm closing this issue for now, if there are any questions, feel free to comment again or create a new issue.
