### ISSUE TITLE
iDeal does not show bank dropdown

### ISSUE THREAD

**Issue by lukelathouwers** [MultiSafepay/magento2-hyva-checkout#20]
I am using your extension to use MSP with the Hyva checkout. For the iDeal method there is no dropdown available to select a specific bank. According to the screenshots on https://www.multisafepay.com/hyva-checkout-multisafepay this should be available.

**Comment by vinodsowdagar** [comment]
Hi @lukelathouwers ,

Thank you for the report!

We have removed the dropdown according to the new iDEAL guidelines, which introduced a profile page where the user selects their issuer. More information about that can be found here: https://ideal.nl/het-nieuwe-ideal

I'll forward your message to our marketing team so they can adjust the screenshots on our Hyva Checkout page.

If there are any questions, feel free to comment again or create a new issue. For now I am closing this one.
